---
title: "Forest Plots"
format: 
  html:
    code-fold: true
    code-tools: true
editor: visual
toc: true
toc-expand: true
---

# Forest Plots

## Setting up in R

R packages.

```{r}
library(tidyverse)
library(magrittr)
library(patchwork)
```

Helper functions.

```{r}

# Function to extract Cox results from a cox_model while noting the reference level,
# variable, flare type, and IBD diagnosis.
extract_cox_results <- function(data,
                                cox_model,
                                variable,
                                flare_type,
                                diagnosis2) {
  data %>%
    dplyr::pull(variable) %>%
    levels() %>%
    # Create tibble to store Cox results including reference level
    {
      tibble(term = paste0(variable, .), variable = variable, level = .)
    } %>%
    dplyr::left_join(
      cox_model %>%
        broom::tidy(exponentiate = TRUE, conf.int = TRUE) %>%
        dplyr::filter(stringr::str_starts(term, variable)),
      by = "term"
    ) %>%
    # Diagnosis
    dplyr::mutate(diagnosis2 = diagnosis2, flare_type = flare_type)
}


# Function to create forest plot for a variable as well as their HR and pvalue
# Custom theme
custom_theme <- 
  theme_minimal() +
  theme(
  # Title
  plot.title = element_text(size = 10),
  plot.subtitle = element_text(size = 8),
  # Axes
  axis.title.y = element_blank()
)

summon_forest_plot <- function(data, variable, diagnosis2){
  
  # Variable and diagnosis2 alias
  variable_value <- variable
  diagnosis2_value <- diagnosis2
  
  # Filter data
  data_plot <- data %>%
    dplyr::filter(
      variable == variable_value,
      diagnosis2 == diagnosis2_value) %>%
    dplyr::arrange(desc(ordering))
  
  plot <- data_plot  %>%
    ggplot(aes(
      x = estimate,
      y = forcats::as_factor(term_tidy),
      xmin = conf.low,
      xmax = conf.high,
      colour = significance
    )) +
    geom_point() +
    geom_errorbarh() +
    geom_vline(xintercept = 1, linetype = "dotted") +
    coord_cartesian(xlim = c(0, 7)) +
    # Legend colours
    scale_colour_manual(
      limits = c("Reference level", "Not Significant", "Significant"),
      values = c("black", "black", "red"),
      drop = FALSE) +
    # Axes labels
    xlab("Hazard Ratio (HR)") +
    # Axes ticks
    scale_x_continuous(
      breaks = seq(0, 6, 1)
    ) +
    custom_theme
  
  # HR
  hr <- data_plot %>%
    ggplot() +
    geom_text(aes(
      x = 0,
      y = forcats::as_factor(term_tidy),
      label = conf.interval.tidy)) +
    theme_void() +
    theme(plot.title = element_text(hjust = 0.5))
  
  # P-value
  p <- data_plot %>%
    ggplot() +
    geom_text(aes(
      x = 0,
      y = forcats::as_factor(term_tidy),
      label = p.value.tidy)) +
    theme_void() +
    theme(plot.title = element_text(hjust = 0.5))
  
  # Return
  list(plot = plot, hr = hr, p = p)
  
}


# Function to create a forest plot containing all variables
# as well as their HR and p value
# Stratified by diagnosis type.

summon_complete_forest <- function(
    data,
    diagnosis2,
    title) {

  # Patient reported flares in UC
  plot_anxiety <- summon_forest_plot(data, variable = 'score_group_anxiety', diagnosis2 = diagnosis2)
  plot_depression <- summon_forest_plot(data, variable = 'score_group_depression', diagnosis2 = diagnosis2)
  plot_exercise <- summon_forest_plot(data, variable = 'MinimumExercise', diagnosis2 = diagnosis2)
  plot_lifeevents <- summon_forest_plot(data, variable = 'AnyLifeEvents', diagnosis2 = diagnosis2)
  plot_sleep <- summon_forest_plot(data, variable = 'SleepDisturbance', diagnosis2 = diagnosis2)
  plot_somatisation <- summon_forest_plot(data, variable = 'somatisation', diagnosis2 = diagnosis2)

  plot_anxiety$plot + 
    (plot_anxiety$hr + 
       labs(title = 'HR (95% CI)') + 
       theme(plot.title = element_text(size = 12))) + 
    (plot_anxiety$p + 
       labs(title = 'P-value') +
       theme(plot.title = element_text(size = 12))) +
   plot_depression$plot + plot_depression$hr +  plot_depression$p +
   plot_exercise$plot + plot_exercise$hr + plot_exercise$p +
   plot_lifeevents$plot + plot_lifeevents$hr + plot_lifeevents$p +
   plot_sleep$plot + plot_sleep$hr + plot_sleep$p +
   plot_somatisation$plot + plot_somatisation$hr + plot_somatisation$p +
    patchwork::plot_layout(
      ncol = 3,
     guides = 'collect',
     axes = 'collect',
     width = c(3, 1, 0.5),
     height = c(3,3,1,1,1,4)
   ) +
   patchwork::plot_annotation(
      title = title
   ) &
    theme(
      plot.title = element_text(hjust = 0.5),
     plot.subtitle = element_text(hjust = 0.5),
      legend.position = "none",
     plot.margin = margin(0, 0, 3, 0))
}

```

Load data.

```{r}
# Load in all the Cox results

filepath <- "/Volumes/igmm/cvallejo-predicct/people/Alex/Predicct2/Data/"

# These are dataframes produced from 4 Cox models (patient reported and hard flare x UC and CD diagnosis) passed to extract_cox_results (see helper functions) for each psychosocial variable.

# HADS
cox_results_hads_anxiety <- readr::read_rds(paste0(filepath, "cox_results_hads_anxiety.rds"))

cox_results_hads_depression <- readr::read_rds(paste0(filepath, "cox_results_hads_depression.rds"))

# Exercise
cox_results_exercise <- readr::read_rds(paste0(filepath, "cox_results_exercise.rds"))

# Alcohol
cox_results_alcohol <- readr::read_rds(paste0(filepath, "cox_results_alcohol.rds"))

# Life Events
cox_results_lifeevents <- readr::read_rds(paste0(filepath, "cox_results_lifeevents.rds"))

# PHQ
cox_results_phq <- readr::read_rds(paste0(filepath, "cox_results_phq.rds"))

# PSQI
cox_results_psqi <- readr::read_rds(paste0(filepath, "cox_results_psqi.rds"))
```

## Data Cleaning

Preparing the data for plotting.

```{r}
# Differentiate between anxiety and depression scores
cox_results_hads_anxiety %<>%
  dplyr::mutate(variable = "score_group_anxiety")

cox_results_hads_depression %<>%
  dplyr::mutate(variable = "score_group_depression")


# Combine
cox_results <- cox_results_hads_anxiety %>%
  dplyr::bind_rows(cox_results_hads_depression) %>%
  dplyr::bind_rows(cox_results_exercise) %>%
  dplyr::bind_rows(cox_results_alcohol) %>%
  dplyr::bind_rows(cox_results_lifeevents) %>%
  dplyr::bind_rows(cox_results_phq) %>%
  dplyr::bind_rows(cox_results_psqi)


# Ordering for plotting?
# Need to do manually
cox_results %<>%
  dplyr::mutate(
    ordering = dplyr::case_when(
      term == 'score_group0-7' ~ 0,
      term == 'score_group8-10' ~ 1,
      term == 'score_group11-21' ~ 2,
      term == 'MinimumExerciseYes' ~ 0,
      term == 'MinimumExerciseNo' ~ 1,
      term == 'weekly_units0-0.1' ~ 0,
      term == 'weekly_units0.1-14' ~ 1,
      term == 'weekly_units>14' ~ 2,
      term == 'AnyLifeEventsNo' ~ 0,
      term == 'AnyLifeEventsYes' ~ 1,
      term == 'somatisationNone' ~ 0,
      term == 'somatisationMild' ~ 1,
      term == 'somatisationModerate' ~ 2,
      term == 'somatisationSevere' ~ 3,
      term == 'SleepDisturbanceNo' ~ 0,
      term == 'SleepDisturbanceYes' ~ 1,
    )
  )

# Tidy up the term
cox_results %<>%
  dplyr::mutate(
    term_tidy = dplyr::case_when(
      term == 'score_group0-7' & variable == 'score_group_anxiety' ~ 'HADS Anxiety Score 0-7',
      term == 'score_group8-10' & variable == 'score_group_anxiety' ~ 'HADS Anxiety Score Score 8-10',
      term == 'score_group11-21' & variable == 'score_group_anxiety' ~ 'HADS Anxiety ScoreScore 11-21',
      term == 'score_group0-7' & variable == 'score_group_depression' ~ 'HADS Depression Score 0-7',
      term == 'score_group8-10' & variable == 'score_group_depression' ~ 'HADS Depression Score Score 8-10',
      term == 'score_group11-21' & variable == 'score_group_depression' ~ 'HADS Depression Score Score 11-21',
      term == 'MinimumExerciseYes' ~ 'Met minimum exercise',
      term == 'MinimumExerciseNo' ~ 'Not met minimum exercise',
      term == 'weekly_units0-0.1' ~ 'Weekly units 0-0.1',
      term == 'weekly_units0.1-14' ~ 'Weekly units 0.1-14',
      term == 'weekly_units>14' ~ 'Weekly units > 14',
      term == 'AnyLifeEventsNo' ~ 'No life events in past month',
      term == 'AnyLifeEventsYes' ~ 'At least 1 life event in past month',
      term == 'somatisationNone' ~ 'No somatisation',
      term == 'somatisationMild' ~ 'Mild somatisation',
      term == 'somatisationModerate' ~ 'Moderate somatisation',
      term == 'somatisationSevere' ~ 'Severe somatisation',
      term == 'SleepDisturbanceNo' ~ 'No sleep disturbance',
      term == 'SleepDisturbanceYes' ~ 'Some sleep disturbance',
    )
  )

# Confidence intervals
cox_results %<>%
  dplyr::mutate(
    conf.interval.tidy = dplyr::case_when(
      (is.na(conf.low) & is.na(conf.high)) ~ "-",
      TRUE ~ paste0(sprintf("%.3g", estimate), " (", sprintf("%.3g", conf.low), " - ", sprintf("%.3g", conf.high), ")")
    )
  )

# Tidy p values
cox_results %<>%
  dplyr::mutate(
    p.value.tidy = dplyr::case_when(
      is.na(p.value) ~ "-",
      TRUE ~ sprintf("%.3g", p.value)
    )
  )

# Significance
cox_results %<>%
  dplyr::mutate(
    significance = dplyr::case_when(
      is.na(p.value) ~ "Reference level",
      p.value <= 0.05 ~ "Significant",
      p.value > 0.05 ~ "Not Significant"
    )
  )

# NA estimates as the reference level of 1
cox_results %<>%
  tidyr::replace_na(
    list(estimate = 1)
  )

# Remove reference group for binary variables (as the reference is obvious)
cox_results %<>%
  dplyr::filter(
    !term == 'MinimumExerciseYes',
    !term == 'AnyLifeEventsNo',
    !term == 'SleepDisturbanceNo'
  )

# Significance as a factor
cox_results %<>%
  dplyr::mutate(
    significance = forcats::as_factor(significance)
  )


# Flare type
cox_results_soft <- cox_results %>%
  dplyr::filter(flare_type == 'soft')

cox_results_hard <- cox_results %>%
  dplyr::filter(flare_type == 'hard')
```

## Plotting

```{r}


# Do separate plots of UC and CD

# Patient reported UC
summon_complete_forest(
  data = cox_results_soft,
  diagnosis2 = 'UC/IBDU',
  title = "Patient reported flare in UC/IBDU"
)

# Patient reported CD
summon_complete_forest(
  data = cox_results_soft,
  diagnosis2 = 'CD',
  title = "Patient reported flare in CD"
)

# Hard UC
summon_complete_forest(
  data = cox_results_hard,
  diagnosis2 = 'UC/IBDU',
  title = "Hard flare in UC/IBDU"
)

# Hard CD
summon_complete_forest(
  data = cox_results_hard,
  diagnosis2 = 'CD',
  title = "Hard flare in CD"
)
```
