---
title: "Introduction"
author:
  - name: "Nathan Constantine-Cooke"
    corresponding: true
    url: https://scholar.google.com/citations?user=2emHWR0AAAAJ&hl=en&oi=ao
    affiliations:
      - ref: CGEM
      - ref: HGU
  - name: "Chiara Cotronei"
    url: https://www.research.ed.ac.uk/en/persons/chiara-cotronei
    affiliations:
      - ref: Lothian
bibliography: Baseline.bib   
---

This section of the website explores the baseline data for the PREdiCCt study,
generating inferences and producing display items for publication.

For all baseline reports, only the _faecal calprotectin_ cohort, the sub-cohort
defined as subjects with baseline faecal calprotectin available, are described
(unless otherwise stated). For each variable considered, associations with
faecal calprotectin categories (<50, 50--250, >250) are presented using
chi-squared tests and ANOVA for categorical and continuous data respectively. In
all cases, only subjects without missing data for FC or the variable of interest
are analysed when associations are being tested for. 

There are three main data sources for baseline demographic and phenotypic data
in PREdiCCt: 

1. Participant questionnaires.
1. Forms completed by a subject's clinical team (via
   [REDCap](https://www.project-redcap.org/)) during recruitment.
1. Data collected retrospectively during the end-of-study (EoS) phenotyping
   which was completed by a member of the subject's IBD care team.

As all three are used, it will be made clear which source the data
presented originate from. 
