---
title: "Alcohol"
author:
  - name: "Nathan Constantine-Cooke"
    corresponding: true
    url: https://scholar.google.com/citations?user=2emHWR0AAAAJ&hl=en&oi=ao
    affiliations:
      - ref: CGEM
      - ref: HGU
  - name: "Víctor Velasco-Pardo"
    url: https://scholar.google.com/citations?user=cR3nbyAAAAAJ&hl=en&oi=ao
    affiliations:
      - ref: CGEM
  - name: "Alexander Rudge"
    affiliations:
      - ref: CGEM
  - name: "Beatriz Gros"
    url: https://scholar.google.com/citations?user=2emHWR0AAAAJ&hl=en&oi=ao
    affiliations:
      - ref: Spain
      - ref: IBD
  - name: "Maiara Brusco De Freitas"
    url: "https://scholar.google.com/citations?user=RfXbXL8AAAAJ&hl=en&oi=ao"
    affiliations:
      - ref: PREDICT
bibliography: Survival.bib
---

## Introduction

```{R}
#| message: false
source("Survival/utils.R")
library(readxl)

# Setup analysis environment
analysis_setup <- setup_analysis()
paths <- analysis_setup$paths
demo <- analysis_setup$demo

flare.df <- readRDS(paste0(paths$outdir, "flares-biochem.RDS"))
flare.cd.df <- readRDS(paste0(paths$outdir, "flares-biochem-cd.RDS"))
flare.uc.df <- readRDS(paste0(paths$outdir, "flares-biochem-uc.RDS"))
```

Data cleaning.

```{r}
# Get Alcohol data from ffq
prefix <- "/Volumes/igmm/cvallejo-predicct/predicct/end-of-follow-up/"

ffq <- read_xlsx(
  paste0(
    prefix,
    "predicct ffq_nutrientfood groupDQI all foods_data (n1092)Nov2022.",
    "xlsx"
  )
)

alcohol <- ffq %>%
  dplyr::select(participantno,
         Alcoholg,
         Alcohol_percEng,
         Alcohol_units,
         Alcohol_units_wk)

alcohol %<>%
  dplyr::rename(ParticipantNo = participantno) %>%
  dplyr::mutate(ParticipantNo = as.character(ParticipantNo))

alcohol %<>% mutate(
    weekly_units = case_when(
      Alcohol_units_wk <= 0.1 ~ "0-0.1",
      Alcohol_units_wk > 0.1 & Alcohol_units_wk <= 14 ~ "0.1-14",
      Alcohol_units_wk > 14 ~ ">14"
    )
  ) %>%
  dplyr::mutate(weekly_units = factor(
    weekly_units,
    levels = c("0-0.1", "0.1-14", ">14")
))

# Join to flare data
flare.df %<>%
  dplyr::left_join(
    alcohol, by = 'ParticipantNo'
  )

flare.uc.df %<>%
  dplyr::left_join(
    alcohol, by = 'ParticipantNo'
  )

flare.cd.df %<>%
  dplyr::left_join(
    alcohol, by = 'ParticipantNo'
  )

```

## Alcohol

### Crohn's Disease

#### Patient reported flare

```{r}
# Kaplan-Meier
flare.cd.df %>%
  survfit(Surv(softflare_time, softflare) ~ weekly_units, data = .) %>%
  ggsurvplot(data = flare.cd.df,
             conf.int = TRUE,
             ggtheme = theme_minimal())

# Cox model
cox_soft_cd <- coxph(
  Surv(softflare_time, softflare) ~
    weekly_units + Sex + cat + IMD + dqi_tot + frailty(SiteNo),
  data = flare.cd.df
)

cox_soft_cd %>%
  broom::tidy(exp = TRUE, conf.int = TRUE)

```

#### Objective flare

```{r}
# Kaplan-Meier
flare.cd.df %>%
  survfit(Surv(hardflare_time, hardflare) ~ weekly_units, data = .) %>%
  ggsurvplot(data = flare.cd.df,
             conf.int = TRUE,
             ggtheme = theme_minimal())

# Cox model
cox_hard_cd <- coxph(
  Surv(hardflare_time, hardflare) ~
    weekly_units + Sex + cat + IMD + dqi_tot + frailty(SiteNo),
  data = flare.cd.df
)

cox_hard_cd %>%
  broom::tidy(exp = TRUE, conf.int = TRUE)

```

### Ulcerative Colitis

#### Patient reported flare

```{r}
# Kaplan-Meier
flare.uc.df %>%
  survfit(Surv(softflare_time, softflare) ~ weekly_units, data = .) %>%
  ggsurvplot(data = flare.uc.df,
             conf.int = TRUE,
             ggtheme = theme_minimal())

# Cox model
cox_soft_uc <- coxph(
  Surv(softflare_time, softflare) ~
    weekly_units + Sex + cat + IMD + dqi_tot + frailty(SiteNo),
  data = flare.uc.df
)

cox_soft_uc %>%
  broom::tidy(exp = TRUE, conf.int = TRUE)


```

#### Objective flare

```{r}
# Kaplan-Meier
flare.uc.df %>%
  survfit(Surv(hardflare_time, hardflare) ~ weekly_units, data = .) %>%
  ggsurvplot(data = flare.uc.df,
             conf.int = TRUE,
             ggtheme = theme_minimal())

# Cox model
cox_hard_uc <- coxph(
  Surv(hardflare_time, hardflare) ~
    weekly_units + Sex + cat + IMD + dqi_tot + frailty(SiteNo),
  data = flare.uc.df
)

cox_hard_uc %>%
  broom::tidy(exp = TRUE, conf.int = TRUE)


```
