---
title: "Flare overview"
author:
  - name: "Nathan Constantine-Cooke"
    corresponding: true
    url: https://scholar.google.com/citations?user=2emHWR0AAAAJ&hl=en&oi=ao
    affiliations:
      - ref: CGEM
      - ref: HGU
bibliography: Survival.bib   
---

## Introduction

```{R}
#| message: false
library(readxl)
library(tidyverse)
library(datefixR)
library(survival)
library(survminer)
library(pander)
library(coxme)
library(finalfit)
library(DescTools)
library(gtsummary)
library(patchwork)

# paths to PREdiCCt data
if (file.exists("/docker")) { # If running in docker
  data.path <- "data/final/20221004/"
  redcap.path <- "data/final/20231030/"
  prefix <- "data/end-of-follow-up/"
  outdir <- "data/processed/"
  followup.dir <- "data/final/20240308/Followup/"
} else { # Run on OS directly
  data.path <- "/Volumes/igmm/cvallejo-predicct/predicct/final/20221004/"
  redcap.path <- "/Volumes/igmm/cvallejo-predicct/predicct/final/20231030/"
  prefix <- "/Volumes/igmm/cvallejo-predicct/predicct/end-of-follow-up/"
  outdir <- "/Volumes/igmm/cvallejo-predicct/predicct/processed/"
  followup.dir <- paste0(
    "/Volumes/igmm/cvallejo-predicct/predicct/final/",
    "20240308/Followup/"
  )
}

demo <- readRDS(paste0(outdir, "demo-full.RDS"))
demo$FC <- log(demo$FC)

cox.summary <- function(fit) {
  cat("Cox model summary:")
  fit %>%
    finalfit::fit2df(condense = FALSE) %>%
    knitr::kable(
      col.names = c(
        "Variable",
        "HR",
        "Lower 95%",
        "Upper 95%",
        "P-value"
      ),
      digits = 4
    ) %>%
    print()
  cat("\ ")

  cat("Diagnostics:\ ")

  cat('::: {.panel-tabset group="diagnostics"}\ ')

  cat("###### Proportional hazards assumption test \ ")
  cox.zph(fit)$table %>%
    knitr::kable(
      col.names = c(
        "",
        "Chi-squared statistic",
        "DF",
        "P-value"
      ),
      digits = 4
    ) %>%
    print()

  cat("###### DF betas \ ")

  print(ggcoxdiagnostics(fit, type = "dfbeta"))

  cat("###### Martignale residuals \n")
  print(ggcoxdiagnostics(fit, type = "martingale", linear.predictions = TRUE))

  cat(":::")
  return()
}
```

This page explores patient-reported and hard flares. Survival curves are
compared across diseases, and patient-reported and hard flares are compared
directly. 

## Response rates

As clinical are largely derived from patient completed questionnaires, it is
worthwhile to first consider how questionnaires were completed for each month. 

As should be expected, there is a small degree of attrition of responses over
time (@fig-responses). However,  there is a large increase at the end of
followup (M24) as additional communications were sent which encouraged the
completion of the final questionnaire. 

```{R}
#| label: fig-responses
#| fig-cap: "Number of responses for each month of follow-up for (A) the whole cohort, (B) the FC cohort, and (C) the FFQ cohort."
#| fig-width: 7
#| fig-height: 15
monthly <- read_xlsx(paste0(data.path, "Followup/monthlyQ.xlsx"))
p1 <- monthly %>%
  mutate(Q_month = paste0("M", Q_month)) %>%
  ggplot(aes(x = factor(Q_month, levels = paste0("M", seq(1, 24))))) +
  geom_bar(fill = "#F17300", color = "#904200") +
  theme_minimal() +
  ylab("Monthly questionnaire responses") +
  xlab("") +
  scale_x_discrete(
    breaks = paste0("M", seq(1, 24, by = 2)),
    labels = paste0("M", seq(1, 24, by = 2))
  ) +
  ylim(0, 1200)



monthly.fc <- monthly %>%
  filter(ParticipantNo %in% subset(demo, !is.na(cat))$ParticipantNo)

p2 <- monthly.fc %>%
  mutate(Q_month = paste0("M", Q_month)) %>%
  ggplot(aes(x = factor(Q_month, levels = paste0("M", seq(1, 24))))) +
  geom_bar(fill = "#A8201A", color = "#6F0802") +
  theme_minimal() +
  ylab("Monthly questionnaire responses") +
  xlab("") +
  scale_x_discrete(
    breaks = paste0("M", seq(1, 24, by = 2)),
    labels = paste0("M", seq(1, 24, by = 2))
  ) +
  ylim(0, 1200)

monthly.ffq <- monthly %>%
  filter(ParticipantNo %in% subset(demo, (!is.na(cat)) & (!is.na(fibre)))$ParticipantNo)

p3 <- monthly.ffq %>%
  mutate(Q_month = paste0("M", Q_month)) %>%
  ggplot(aes(x = factor(Q_month, levels = paste0("M", seq(1, 24))))) +
  geom_bar(fill = "#0F8B8D", color = "#005354") +
  theme_minimal() +
  ylab("Monthly questionnaire responses") +
  xlab("Month of follow-up") +
  scale_x_discrete(
    breaks = paste0("M", seq(1, 24, by = 2)),
    labels = paste0("M", seq(1, 24, by = 2))
  ) +
  ylim(0, 1200)

p <- p1 / p2 / p3 +
  plot_annotation(tag_levels = "A") &
  theme(plot.tag = element_text(face = "bold", size = 18))


ggsave("plots/response-rate.pdf", p, width = 7, height = 15)
ggsave("plots/response-rate.png", p, width = 7, height = 15)
p
```

## Primary outcome: First patient-reported flare

```{R}
#| warning: false
flares <- read_xlsx(
  paste0(followup.dir, "all-flares.xlsx"),
  na = ".",
  sheet = 1
) %>%
  select(ParticipantNo, softflare, softflare_time, hardflare, hardflare_time)

flare.df <- merge(demo, flares, by = "ParticipantNo")
```

For patient-reported flares, a  flare is primarily defined by a subject
reporting their disease as uncontrolled. The time of the flare is given by the
date the subject reported their symptoms worsening. 

If a date for when the symptoms worsened is given, but the subject did not
answer if their disease was uncontrolled, it is assumed their disease is not
controlled (in other words, it is assumed a patient-reported flare occurred).

If a subject reported their disease as being uncontrolled, but did not give a
date for the worsening of their symptoms, then the earliest date given for
either an IBD outpatient appointment, emergency hospital admission, call with
their IBD care team, or surgery in the questionnaire response was used. If none
of these dates were provided then the date of the questionnaire response was
used instead. 

If a hard flare occurs prior to a patient-reported flare then the
patient-reported flare is assumed to occur on the same date as the hard flare.

A complete description of the steps taken to calculate patient-reported flares
is outlined in the below drop-down section. 

<details>
<summary> Steps for calculating patient-reported flares </summary>

1. If date of flare is before date of entry to study, then delete flare date and
   recode diseasecontrolled as 1.
2. If flare date is after the questionnaire date (I.E in the future), reset
   flare date to questionnaire date.
3. If questionnaire completed after date of withdrawal, remove.
4. If date of flare is >2 years after entry, censor patient-reported flare at 2
   years.
5. Time is earliest of flare time or end of follow up, from entry date.
6. All data censored at 2 years.
7. Including the hard flares (hard flare data are much more straightforward,
   flare=`diseaseflareyn` and flare date=`firstflarestartdate` from EOS data)
    * If both datasets say no flare, patient-reported flare is no and follow up time from
      hard flare <= 2 years, patient-reported flare time is longest of
      questionnaire and hard flare times
    * If both datasets say no flare, patient-reported flare is no and follow up
      time from hard flare > 2 years, patient-reported time is 2 years
    * If no flare in questionnaires, but hard flare reported before 2 years of
      follow up, take hard flare data
    * If no flare in questionnaires, but hard flare reported after 2 years,
      patient-reported flare is no and patient-reported flare time is 2 years
    * If flare in questionnaire and no hard flare, patient-reported flare from
      questionnaire data
    * If flare in questionnaire and also hard flare, take the earliest time
    * If questionnaire data is missing and no hard flare, patient-reported flare
      is no and time is earliest of hard flare follow up and 2 years
    * If questionnaire data is missing and hard flare reported within 2 years,
      patient-reported flare data are taken from hard flare data
    * If questionnaire data is missing and hard flare reported after 2 years
      then patient-reported flare is no and time is 2 years
    * Otherwise if questionnaire data is not missing and hardflare is, then
      patient-reported flare is taken from questionnaire data

All times are taken from the earliest reported flare.

</details>

```{R}
#| label: fig-km-soft
#| fig-cap: "Kaplan-Meier curves for patient-reported flares stratified by IBD type."
#| fig-height: 6.5

fit <- flare.df %>%
  drop_na(cat) %>%
  survfit(Surv(softflare_time, softflare) ~ diagnosis2, data = .)
p <- ggsurvplot(fit,
  data = flare.df,
  conf.int = TRUE,
  pval = TRUE,
  pval.method = TRUE,
  ggtheme = theme_minimal(),
  risk.table = TRUE,
  legend.title = "IBD type",
  legend.labs = c("Crohn's disease", "UC/IBDU"),
  tables.y.text = FALSE,
  palette = c("#4F6D7A", "#02C3BD"),
  xlab = "Time from study recrutiment (days)",
  tables.col = "strata"
)
saveRDS(p, paste0(outdir, "flare-soft.RDS"))
print(p, newpage = FALSE)
```

## Secondary outcome: first hard flare

Disease flares been reported by clinical care teams instead of being
reported by subjects themselves.

```{R}
#| fig-height: 6.5
#| label: fig-km-hard-cutoff
#| fig-cap: "Kaplan-Meier curves of hard flares stratified by IBD type across the first two years."

flare.df.cutoff <- flare.df %>%
  mutate(
    hardflare = if_else(hardflare_time > 730.5, 0, hardflare),
    hardflare_time = if_else(hardflare_time > 730.5, 730.5, hardflare_time)
  )

fit <- survfit(Surv(hardflare_time, hardflare) ~ diagnosis2,
  data = flare.df.cutoff
)
p <- ggsurvplot(fit,
  data = flare.df.cutoff,
  conf.int = TRUE,
  pval = TRUE,
  pval.method = TRUE,
  ggtheme = theme_minimal(),
  risk.table = TRUE,
  legend.title = "IBD type",
  legend.labs = c("Crohn's disease", "UC/IBDU"),
  tables.y.text = FALSE,
  palette = c("#4F6D7A", "#02C3BD"),
  xlab = "Time from study recrutiment (days)",
  break.time.by = 200,
  tables.col = "strata"
)
print(p, newpage = FALSE)
```


```{R}
#| fig-height: 6.5
#| label: tbl-hard-full
#| tbl-cap: "Hard flare survival rates across the full follow-up."

fit <- survfit(Surv(hardflare_time, hardflare) ~ 1, data = flare.df)
p <- ggsurvplot(fit,
  data = flare.df,
  conf.int = TRUE,
  pval = TRUE,
  pval.method = TRUE,
  ggtheme = theme_minimal(),
  risk.table = TRUE,
  palette = c("#4F6D7A", "#02C3BD"),
  xlab = "Time from study recrutiment (days)",
  break.time.by = 400
)

fit %>%
  tbl_survfit(
    times = max(flare.df$hardflare_time, na.rm = TRUE),
    statistic = "{estimate} ({conf.low}, {conf.high})",
    label_header = "**Survival across full follow-up (95% CI)**"
  )
```


```{R}
#| fig-height: 6.5
#| label: fig-km-hard-diag
#| fig-cap: "Kaplan-Meier curves of hard flares stratified by IBD type across the full follow-up."
fit <- survfit(Surv(hardflare_time, hardflare) ~ diagnosis2, data = flare.df)
p <- ggsurvplot(fit,
  data = flare.df,
  conf.int = TRUE,
  pval = TRUE,
  pval.method = TRUE,
  ggtheme = theme_minimal(),
  risk.table = TRUE,
  palette = c("#4F6D7A", "#02C3BD"),
  xlab = "Time from study recrutiment (days)",
  legend.title = "IBD type",
  legend.labs = c("Crohn's disease", "UC/IBDU"),
  break.time.by = 400,
  tables.y.text = FALSE
)
saveRDS(p, paste0(outdir, "flare-hard.RDS"))
print(p, newpage = FALSE)
```


```{R}
fit %>%
  tbl_survfit(
    times = max(flare.df$hardflare_time, na.rm = TRUE),
    label = "IBD type",
    statistic = "{estimate} ({conf.low}, {conf.high})",
    label_header = "**Survival across full follow-up (95% CI)**"
  )
```

## Comparison of hard and patient-reported flares 

```{R}
#| fig-height: 6.5
#| label: fig-comb-comp
#| fig-cap: "Survival curves for patient-reported and hard flares."
flare.comb <- rbind(
  data.frame(
    ParticipantNo = flares$ParticipantNo,
    Cens = flares$hardflare,
    time = flares$hardflare_time,
    type = "Hard flare"
  ),
  data.frame(
    ParticipantNo = flares$ParticipantNo,
    Cens = flares$softflare,
    time = flares$softflare_time,
    type = "Patient-reported flare"
  )
)

flare.comb <- flare.comb %>%
  drop_na(Cens, time)


flare.comb$type <- factor(flare.comb$type,
  levels = c("Hard flare", "Patient-reported flare")
)


fit <- survfit(Surv(time, Cens) ~ type, data = flare.comb)


p <- ggsurvplot(fit,
  data = flare.comb,
  conf.int = TRUE,
  pval = FALSE,
  pval.method = FALSE,
  ggtheme = theme_minimal(),
  risk.table = TRUE,
  palette = c("#DD6E42", "#EE1B65"),
  xlab = "Time from study recrutiment (days)",
  legend.title = "Flare type",
  legend.labs = c("Hard flare", "Patient-reported flare"),
  tables.y.text = FALSE,
  tables.col = "strata",
  break.time.by = 300,
  xlim = c(0, 2200)
)

cairo_pdf("plots/flare-comparison.pdf", width = 7, height = 7)
print(p, newpage = FALSE)
invisible(dev.off())
saveRDS(p, paste0(outdir, "flare-comparison.RDS"))
print(p, newpage = FALSE)
```


```{R}
#| label: tbl-comb-comp
#| tbl-cap: "Survival rates after two years of follow-up."

fit %>%
  tbl_survfit(
    times = 365 * 2,
    label = "Flare type",
    statistic = "{estimate} ({conf.low}, {conf.high})",
    label_header = "**2-year survival (95% CI)**"
  )

fit %>%
  tbl_survfit(
    times = 365.25 * 4,
    label = "Flare type",
    statistic = "{estimate} ({conf.low}, {conf.high})",
    label_header = "**5-year survival (95% CI)**"
  )


```


```{R}
#| label: tbl-comb-comp-cd
#| tbl-cap: "Survival rates after two years of follow-up for Crohn's disease only."

flare.comb.cd <- flare.comb %>%
  merge(demo[, c("ParticipantNo", "diagnosis2")], by = "ParticipantNo") %>%
  filter(diagnosis2 == "CD") %>%
  select(-diagnosis2)

fit.cd <- survfit(Surv(time, Cens) ~ type, data = flare.comb.cd)

fit.cd %>%
  tbl_survfit(
    times = 365 * 2,
    label = "Flare type",
    statistic = "{estimate} ({conf.low}, {conf.high})",
    label_header = "**2-year survival (95% CI)**"
  )
```


```{R}
#| label: tbl-comb-comp-uc
#| tbl-cap: "Survival rates after two years of follow-up for ulcerative colitis/IBDU only."

flare.comb.uc <- flare.comb %>%
  merge(demo[, c("ParticipantNo", "diagnosis2")], by = "ParticipantNo") %>%
  filter(diagnosis2 == "UC/IBDU") %>%
  select(-diagnosis2)

fit.uc <- survfit(Surv(time, Cens) ~ type, data = flare.comb.uc)

fit.uc %>%
  tbl_survfit(
    times = 365 * 2,
    label = "Flare type",
    statistic = "{estimate} ({conf.low}, {conf.high})",
    label_header = "**2-year survival (95% CI)**"
  )
```


```{R}
#| include: false
count <- 0
for (id in unique(flare.comb$ParticipantNo)) {
  temp <- subset(flare.comb, ParticipantNo == id)
  if (nrow(temp) == 2) {
    if (all(temp$Cens == 1)) {
      if (temp[1, "time"] == temp[2, "time"]) {
        count <- count + 1
      }
    }
  }
}
```

```{R}
saveRDS(flare.df, paste0(outdir, "flares-overview.RDS"))
```

## Reproduction and reproducibility {.appendix}

<details class = "appendix">
  <summary> Session info </summary>

```{R Session info}
#| echo: false
pander::pander(sessionInfo())
```

</details>

Licensed by 
<a href="https://creativecommons.org/licenses/by/4.0/">CC BY</a>
 unless otherwise stated.
