---
title: "About"
date: ""
date-format: ""
title-block-banner: false
author:
  - name: "Nathan Contantine-Cooke" 
    url: https://scholar.google.com/citations?user=2emHWR0AAAAJ&hl=en&oi=ao
    corresponding: true
    affiliations:
      - ref: HGU
      - ref: CGEM
---

```{R}
#| echo: false
# At least one R code block has to exist or inline doesn't work
```

## Introduction

The PREdiCCt study ([NCT03282903](https://clinicaltrials.gov/study/NCT03282903))
is a UK-wide prospective study of inflammatory bowel disease (IBD) patients. 

The study aimed to determine which aspects of a) baseline habitual diet, b) the
environment, c) genetic variation, and d) the gut microbiota, predict disease
flare in Crohn’s disease and/or ulcerative colitis and IBD unclassified (IBDU).

Participants were recruited in remission and were extensively phenotyped via
questionnaires completed by patients and care teams. Saliva and stool samples
were collected for genetic and microbiome sequencing. Participants were then
followed until disease flare.

This work uses data provided by patients and collected by the NHS as part of
their care and support. We are grateful to participants and their IBD care
teams for their support. 

## Using this website

The code button at the top of each page can
be used to show all code blocks instead of clicking on the code buttons for each
individual block of code. Moving the mouse pointer over citations will produce a
pop up box with reference details. Clicking on the citation will link to the
bibliography at the bottom of the page. 

## Software versions

All analyses have been generated using
[`{r} strsplit(R.version$version.string, " (", fixed = TRUE)[[1]][1]`](https://www.r-project.org).
Please see the Session Information sections at the bottom of each report to see
the R packages used for that particular analysis and the respective package
versions. 

## {.appendix}

This website has been generated using the [Quarto](https://quarto.org)
scientific publishing system built on [pandoc](https://pandoc.org). 
